/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  POAPFactoryABI,
  POAPFactoryABIInterface,
  IPOAPFactory,
} from "../POAPFactoryABI";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "diamondCutFacetAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "diamondLoupeFacetAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "nestableFacetAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "multiAssetFacetAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "equippableFacetAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "collectionMetadataFacetAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "initContractAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "implContractAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "poapMintModuleAddress",
            type: "address",
          },
          {
            internalType: "address",
            name: "travelNotesAddress",
            type: "address",
          },
          {
            components: [
              {
                internalType: "address",
                name: "facetAddress",
                type: "address",
              },
              {
                internalType: "enum IDiamondCut.FacetCutAction",
                name: "action",
                type: "uint8",
              },
              {
                internalType: "bytes4[]",
                name: "functionSelectors",
                type: "bytes4[]",
              },
            ],
            internalType: "struct IDiamondCut.FacetCut[]",
            name: "cuts",
            type: "tuple[]",
          },
        ],
        internalType: "struct IPOAPFactory.ConstructParams",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "instanceAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "deployer",
        type: "address",
      },
    ],
    name: "POAPCreated",
    type: "event",
  },
  {
    inputs: [],
    name: "collectionMetadataAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cuts",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "facetAddress",
            type: "address",
          },
          {
            internalType: "enum IDiamondCut.FacetCutAction",
            name: "action",
            type: "uint8",
          },
          {
            internalType: "bytes4[]",
            name: "functionSelectors",
            type: "bytes4[]",
          },
        ],
        internalType: "struct IDiamondCut.FacetCut[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "string",
            name: "fallbackURI",
            type: "string",
          },
          {
            internalType: "string",
            name: "collectionMetadataURI",
            type: "string",
          },
        ],
        internalType: "struct POAPInit.InitStruct",
        name: "initStruct",
        type: "tuple",
      },
    ],
    name: "deployPOAP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "equippableFacetAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "implContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "multiAssetFacetAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nestableFacetAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poapMintModuleAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "travelNotesAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class POAPFactoryABI__factory {
  static readonly abi = _abi;
  static createInterface(): POAPFactoryABIInterface {
    return new utils.Interface(_abi) as POAPFactoryABIInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): POAPFactoryABI {
    return new Contract(address, _abi, signerOrProvider) as POAPFactoryABI;
  }
}
